apiVersion: v1
kind: Service
metadata:
  name: math-auth
  labels:
    k8s-app: math-auth
spec:
  ports:
    - port: 49161
      protocol: TCP
      targetPort: 3000
      nodePort: 32001
  selector:
    k8s-app: math-auth
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - hostname: localhost