apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-auth
  labels:
    k8s-app: math-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: math-auth
  template:
    metadata:
      name: math-auth
      creationTimestamp: null
      labels:
        k8s-app: math-auth
    spec:
      containers:
        - name: math-auth
          image: machripe/math-auth
          resources: {}
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst